[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build]
args = ["build-bpf", "--", "${@}"]
command = "cargo"

[tasks.idl]
args = ["${@}"]
script = """
mkdir -p target/deploy
output = exec anchor idl parse --file programs/gfx-ssl/src/lib.rs
writefile target/deploy/gfx-ssl.json ${output.stdout}

output = exec anchor idl parse --file programs/gfx-controller/src/lib.rs
writefile target/deploy/gfx-controller.json ${output.stdout}
"""
script_runner = "@duckscript"

[tasks.pair_layout]
script = """
cargo test --features "type-layout" --test pair_layout -- --nocapture
"""

[tasks.sol_usdc_test]
script = """
cd sdk
LD_LIBRARY_PATH="./lib" cargo test --test sol_usdc_pair -- --nocapture
"""
